### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by RDKRACZ** [flathub/net.danigm.loop#1]
![image](https://user-images.githubusercontent.com/43277609/159922042-6c7d5770-fe17-4698-b80d-c75e554ec458.png)
![image](https://user-images.githubusercontent.com/43277609/159922080-b6c6bbc0-126d-4bb7-905f-c922a2de159b.png)

**Comment by hfiguiere** [comment]
This is an upstream bug as this text is provided by the appstream file that comes from the upstream developers.

**Comment by hfiguiere** [comment]
See https://gitlab.gnome.org/danigm/loop

**Comment by danigm** [comment]
Just fixed upstream now: https://gitlab.gnome.org/danigm/loop/-/commit/e2abe0946dde3c3dbfaff2df8b5d28d0642b4482

Thanks for the report!
