### ISSUE TITLE
Categories are missing from appstream data

### ISSUE THREAD

**Issue by bbhtt** [flathub/net.danigm.loop#3]
This is due to the desktop file having a low quality category that is filtered by appstream
Please define a proper category from https://specifications.freedesktop.org/menu-spec/latest/apa.html

https://gitlab.gnome.org/danigm/loop/-/blob/084b5ae155502f8876af98ed9833b315bf923160/data/net.danigm.loop.desktop.in#L7

**Comment by yakushabb** [comment]
Fixed.
